# Generated by Django 5.1.5 on 2025-03-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryWiseResumesScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
